### ISSUE TITLE
npx fails on when using daemon flag on ubuntu

### ISSUE THREAD

**Issue by kumpmati** [KvanttoriOy/huukki#7]
Works correctly when running `npx @kvanttori/huukki`. The `npx @kvanttori/huukki --daemon` command also installs and starts the pm2 process correctly, but running `pm2 logs huukki` reveals this:

```bash
Error: Cannot find module '/home/ubuntu/.npm/_npx/24057/lib/node_modules/@kvanttori/huukki/dist/index.js'
2|huukki   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2|huukki   |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
2|huukki   |     at Object.<anonymous> (/home/ubuntu/.npm-global/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2|huukki   |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2|huukki   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2|huukki   |     at Module.load (internal/modules/cjs/loader.js:950:32)
2|huukki   |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2|huukki   |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
2|huukki   |     at internal/main/run_main_module.js:17:47 {
2|huukki   |   code: 'MODULE_NOT_FOUND',
2|huukki   |   requireStack: []
2|huukki   | }
```

**Comment by kumpmati** [comment]
Works sometimes, no idea why
